LAYERS = openembedded-core meta-openembedded meta-arm meta-rauc meta-emos

# Bitbake is special: it does not contain a layer, so it is not added to LAYERS
bitbake_repo              = https://git.openembedded.org/bitbake
bitbake_branch            = 2.8
bitbake_commit            = yocto-5.0.20

openembedded-core_repo    = https://git.openembedded.org/openembedded-core
openembedded-core_branch  = scarthgap
# Choose commit past tag 'yocto-5.0.20' to include recent CVE patches
openembedded-core_commit  = 07ca97baad7b182849ee50f0bd629b68dc9f53b3
openembedded-core_subdirs = meta

meta-openembedded_repo    = https://git.openembedded.org/meta-openembedded
meta-openembedded_branch  = scarthgap
# Choose higher commit to include CVE fixes
meta-openembedded_commit  = b5874ea07d69919d9b40d59f2c2f0bbd24bc3259
meta-openembedded_subdirs = meta-multimedia meta-networking meta-oe meta-python meta-webserver

meta-arm_repo             = https://git.yoctoproject.org/meta-arm
meta-arm_branch           = scarthgap
meta-arm_commit           = yocto-5.0.3
meta-arm_subdirs          = meta-arm-toolchain meta-arm

meta-rauc_repo            = https://github.com/rauc/meta-rauc.git
meta-rauc_branch          = scarthgap
meta-rauc_commit          = d63878f20eba7a85ecf53566e7a3377e78bb46ac

meta-emos_repo            = https://github.com/tq-systems/meta-emos.git
meta-emos_branch          = v9.1.0
