LAYERS = openembedded-core meta-openembedded meta-arm meta-ti meta-rauc meta-emos

# Bitbake is special: it does not contain a layer, so it is not added to LAYERS
bitbake_repo              = https://git.openembedded.org/bitbake
bitbake_branch            = 2.8
bitbake_commit            = yocto-5.0.17

openembedded-core_repo    = https://git.openembedded.org/openembedded-core
openembedded-core_branch  = scarthgap
openembedded-core_commit  = yocto-5.0.17
openembedded-core_subdirs = meta

meta-openembedded_repo    = https://git.openembedded.org/meta-openembedded
meta-openembedded_branch  = scarthgap
meta-openembedded_commit  = 5124ac4a658899158f4a7a2ddf1d2ca931ec7d0e
meta-openembedded_subdirs = meta-multimedia meta-networking meta-oe meta-python meta-webserver

meta-arm_repo             = https://git.yoctoproject.org/meta-arm
meta-arm_branch           = scarthgap
meta-arm_commit           = a81c19915b5b9e71ed394032e9a50fd06919e1cd
meta-arm_subdirs          = meta-arm-toolchain meta-arm

meta-ti_repo              = https://git.yoctoproject.org/meta-ti
meta-ti_branch            = scarthgap
meta-ti_commit            = 11.02.13
meta-ti_subdirs           = meta-ti-bsp

meta-rauc_repo            = https://github.com/rauc/meta-rauc.git
meta-rauc_branch          = scarthgap
meta-rauc_commit          = d63878f20eba7a85ecf53566e7a3377e78bb46ac

meta-emos_repo            = https://github.com/tq-systems/meta-emos.git
meta-emos_branch          = master
