LAYERS = openembedded-core meta-openembedded meta-arm meta-ti meta-rauc meta-cyclonedx meta-emos


# Bitbake is special: it does not contain a layer, so it is not added to LAYERS
bitbake_repo              = https://git.openembedded.org/bitbake
bitbake_branch            = 2.8
bitbake_commit            = 10118785e4a670bce4980e1044c0888a8b6e84af

openembedded-core_repo    = https://git.openembedded.org/openembedded-core
openembedded-core_branch  = scarthgap
openembedded-core_commit  = a1f4ae4e569bc0e36c27c1e4651e502e54d63b28
openembedded-core_subdirs = meta

meta-openembedded_repo    = https://git.openembedded.org/meta-openembedded
meta-openembedded_branch  = scarthgap
meta-openembedded_commit  = 4d3e2639dec542b58708244662d5ce36810fc510
meta-openembedded_subdirs = meta-multimedia meta-networking meta-oe meta-python meta-webserver

meta-arm_repo             = https://git.yoctoproject.org/meta-arm
meta-arm_branch           = scarthgap
meta-arm_commit           = a81c19915b5b9e71ed394032e9a50fd06919e1cd
meta-arm_subdirs          = meta-arm-toolchain meta-arm

meta-ti_repo              = https://git.yoctoproject.org/meta-ti
meta-ti_branch            = scarthgap
meta-ti_commit            = 5258ee2f903d8f1e0cbcb9d01488d08b57314009
meta-ti_subdirs           = meta-ti-bsp

meta-rauc_repo            = https://github.com/rauc/meta-rauc.git
meta-rauc_branch          = scarthgap
meta-rauc_commit          = a687885f3f3ebfcab5865a587a2f0ac8e591899e

meta-cyclonedx_repo       = https://github.com/savoirfairelinux/meta-cyclonedx.git
meta-cyclonedx_branch     = scarthgap
meta-cyclonedx_commit     = f30113516223e8a59e4ebd141e338cfad5a7ddd4

meta-emos_repo            = https://github.com/tq-systems/meta-emos.git
meta-emos_branch          = release/9.0.x
meta-emos_commit          = 1e0017725e390be833788e89b0df247e365e6b78
